const mongoose = require("mongoose")

const vehicleSchema= new mongoose.Schema({
   vin:{
        type:String,
        require:true
    },
   details:{
    type:Object,
    default:{
      year:{
         type:Number,
         default:0
      },
      make:{
         type:String,
         default:""
      },
      make:{
         type:String,
         default:""
      },
      trim:{
         type:String,
         default:""
      },
      style:{
         type:String,
         default:""
      },
      type:{
         type:String,
         default:""
      },
      size:{
         type:String,
         default:""
      },
      made_in:{
         type:String,
         default:""
      },
      made_in_city:{
         type:String,
         default:""
      },
      door:{
         type:Number
      },
      fuel_type:{
         type:String,
         default:""
      },
      fuel_capacity:{
         type:Number
      },
      city_mileage:{
         type:String,
         default:""
      },
      highway_mileage:{
         type:String,
         default:""
      },
      engine:{
         type:String,
         default:""
      },
      engine_size:{
         type:String,
         default:""
      },
      engine_cylinders:{
         type:String,
         default:""
      },
      transmission:{
         type:String,
         default:""
      },
      transmission_type:{
         type:String,
         default:""
      },
      transmission_speeds:{
         type:String,
         default:""
      },
      drivetrain:{
         type:String,
         default:""
      },
      anti_brake_system:{
         type:String,
         default:""
      },
      steering_type:{
         type:String,
         default:""
      },
      curb_weight:{
         type:String,
         default:""
      },
      gross_vehicle_weight_rating:{
         type:String,
         default:""
      },
      overall_height:{
         type:Number
      },
      overall_length:{
         type:Number
      },
      overall_width:{
         type:Number
      },
      wheelbase_length:{
         type:Number
      },
      standard_seating:{
         type:Number
      },
      invoice_price:{
         type:Number
      },
      delivery_chargers:{
         type:Number
      },
      manufacturer_suggested_retail_price:{
         type:Number
      },
      sellingPrice:{
         type:Number
      },
      color:{
         type:String,
         default:""
      },
      cityMileageMin:{
         type:Number
      },
      cityMileageMax:{
         type:Number
      },
      highwayMileageMin:{
         type:Number
      },
      highwayMileageMax:{
         type:Number
      },


    }
   },
   images:{
    type:Object,
    default:{}
   },
   status:{
      type:String,
      default:"active"
   },
   customDetails:{
      type:Object,
      default:{}
      
   }
})

module.exports= mongoose.model("vehicle",vehicleSchema)